permissions:
  contents: read

name: Daily Reports
on:
  schedule:
    # Every day at UTC 03:00
    - cron: "0 3 * * 1,2,3,4,5"
  workflow_dispatch:

jobs:
  sdk-integration-test:
    name: Integration Test - SDK
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false

      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust

      - name: Install ethrex
        run: |
          curl -L https://github.com/lambdaclass/ethrex/releases/latest/download/ethrex-linux_x86_64 -o /usr/local/bin/ethrex
          chmod +x /usr/local/bin/ethrex
          ethrex --version
          echo "ethrex installed successfully"
      - name: Run ethrex l2 --dev
        run: |
          ethrex l2 --dev &

      - name: Wait for ethrex l2
        run: |
          for i in {1..20}; do
            if nc -z localhost 3900; then
              echo "ProofCoordinator ready!"
              exit 0
            fi
            sleep 5
          done
          echo "ProofCoordinator not ready in time"
          exit 1

      - name: Start Prover
        run: |
          ethrex l2 prover --proof-coordinator http://localhost:3900 &

      - name: Run tests
        run: |
          cd /home/runner/work/rex/rex/sdk
          PROPOSER_COINBASE_ADDRESS=0x0007a881CD95B1484fca47615B64803dad620C8d cargo test --package rex-sdk --test tests -- --nocapture --test-threads=1

  cli-integration-test:
    name: Integration Test - CLI
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false

      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust

      - name: Install ethrex
        run: |
          curl -L https://github.com/lambdaclass/ethrex/releases/latest/download/ethrex-linux_x86_64 -o /usr/local/bin/ethrex
          chmod +x /usr/local/bin/ethrex
          ethrex --version
          echo "ethrex installed successfully"

      - name: Run ethrex l2 --dev
        run: |
          ethrex l2 --dev &

      - name: Wait for ethrex l2
        run: |
          for i in {1..20}; do
            if nc -z localhost 3900; then
              echo "ProofCoordinator ready!"
              exit 0
            fi
            sleep 5
          done
          echo "ProofCoordinator not ready in time"
          exit 1

      - name: Start Prover
        run: |
          ethrex l2 prover --proof-coordinator http://localhost:3900 &

      - name: Run tests
        run: |
          cd /home/runner/work/rex/rex
          make cli
          cd cli
          PROPOSER_COINBASE_ADDRESS=0x0007a881CD95B1484fca47615B64803dad620C8d cargo test --package rex --test tests -- --nocapture --test-threads=1

  post-daily-report:
    name: Post report to slack
    runs-on: ubuntu-latest
    needs: [sdk-integration-test, cli-integration-test]
    if: ${{ always() && needs.sdk-integration-test.result != 'skipped' && needs.cli-integration-test.result != 'skipped' }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Check if any job failed
        env:
          SLACK_WEBHOOK: >
            ${{ github.event_name == 'workflow_dispatch'
              && secrets.TEST_CHANNEL_SLACK
              || secrets.ETHREX_L2_SLACK_WEBHOOK
            }}
        run: |
          if [ "${{ needs.sdk-integration-test.result }}" != "success" ]; then
            sh .github/scripts/publish_report.sh "$SLACK_WEBHOOK" "Rex SDK is not working with the latest ethrex version."
          fi
          if [ "${{ needs.cli-integration-test.result }}" != "success" ]; then
            sh .github/scripts/publish_report.sh "$SLACK_WEBHOOK" "Rex CLI is not working with the latest ethrex version."
          fi
          echo "Sending Results" >> $GITHUB_STEP_SUMMARY
